version: "3.9"
services:
  db:
    container_name: pg_container_exchange
    image: postgis/postgis:11-2.5-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exchange
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./simpleData:/var/lib/postgresql/simpledata/
  pgadmin:
    container_name: pgadmin4_container_exchange
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  web:
    build: .
    command: python exchangeProject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/exchangeProject
    ports:
      - "8000:8000"
    depends_on:
      - db