# Generated by Django 4.0 on 2021-12-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromcurrency', models.CharField(blank=True, max_length=256, null=True)),
                ('tocurrency', models.CharField(blank=True, max_length=256, null=True)),
                ('value', models.FloatField()),
                ('last_refresh', models.DateField()),
            ],
        ),
    ]
