# Generated by Django 4.0 on 2021-12-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='fromcurrency',
            new_name='from_currency',
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='tocurrency',
            new_name='to_currency',
        ),
    ]
