# Generated by Django 4.0 on 2021-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_rename_fromcurrency_exchangerate_from_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='last_refresh',
            field=models.DateTimeField(),
        ),
    ]
